name: AI Engine Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "ai-engine/**"
      - "ci/github/workflows/ai-tests.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "ai-engine/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ai-engine
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        working-directory: ai-engine
        run: |
          flake8 inference/ training/ evaluation/ --count --select=E9,F63,F7,F82 || true

      - name: Run model tests
        working-directory: ai-engine
        run: |
          pytest -v || true

      - name: Run evaluation
        working-directory: ai-engine
        run: |
          python evaluation/evaluate_models.py || true